# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h2J_O_daXG2woTXFDhvFWxpk_h17CzBj
"""

# optimized recursion (for the first set of numbers)

import time
import matplotlib.pyplot as plt

def fib(n):
    n1 = 0
    n2 = 1
    if n == 0:
        return n1
    elif n == 1:
        return n2
    else:
        for i in range(2, n):
            f = n1 + n2
            n1 = n2
            n2 = f
        return n2

x = [5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 35, 37, 40, 42, 45]
y = []

for n in x:
    start = time.time()
    result = fib(n)
    end = time.time()
    y.append(end - start)
    print(f"Fibonacci({n}) = {result}, Time taken: {end - start} seconds")

plt.plot(x, y, marker='o')
plt.title('Optimized recursion implementation')
plt.xlabel('Input (n)')
plt.ylabel('Time (seconds)')
plt.show()

# optimized recursion (for the second set of numbers)

import time
import matplotlib.pyplot as plt

def fib(n):
    n1 = 0
    n2 = 1
    if n == 0:
        return n1
    elif n == 1:
        return n2
    else:
        for i in range(2, n):
            f = n1 + n2
            n1 = n2
            n2 = f
        return n2

x = [501, 631, 794, 1000,1259, 1585, 1995, 2512, 3162, 3981, 5012, 6310, 7943, 10000, 12589, 15849]
y = []

for n in x:
    start = time.time()
    result = fib(n)
    end = time.time()
    y.append(end - start)
    print(f"Fibonacci({n}) = {result}, Time taken: {end - start} seconds")

plt.plot(x, y, marker='o')
plt.title('Optimized recursion implementation')
plt.xlabel('Input (n)')
plt.ylabel('Time (seconds)')
plt.show()