# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h2J_O_daXG2woTXFDhvFWxpk_h17CzBj
"""

#recursive method ( first set of numbers)

import time
import matplotlib.pyplot as plt

def fib(n):
  if n==0:
    return 0;
  elif n == 1:
    return 1
  else:
    return fib (n-1)+fib(n-2)

x = [5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 35, 37, 40, 42, 45]
y = []

for n in x:
    start = time.time()
    result = fib(n)
    end = time.time()
    y.append(end - start)
    print(f"Fibonacci({n}) = {result}, Time taken: {end - start:} seconds")

plt.plot(x, y, marker='o')
plt.title('Recursive implementation')
plt.xlabel('Input (n)')
plt.ylabel('Time (seconds)')
plt.show()