# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pWjSLPNa5e5tcPrTgEE-R4wRceWFE8n
"""

import time
import matplotlib.pyplot as plt

start = time.time()

def insertionSort(input):
    for i in range(1, len(input)):
        key = input[i]
        j = i - 1
        while j >= 0 and key < input[j]:
            input[j + 1] = input[j]
            j -= 1
        input[j + 1] = key


start1 = time.time()
insertionSort(input100)
end1 = time.time()

start2 = time.time()
insertionSort(input500)
end2 = time.time()

start3 = time.time()
insertionSort(input1000)
end3 = time.time()

start4 = time.time()
insertionSort(input1500)
end4 = time.time()

start5 = time.time()
insertionSort(input2000)
end5 = time.time()

start6 = time.time()
insertionSort(input2500)
end6 = time.time()

start7 = time.time()
insertionSort(input3000)
end7 = time.time()

start8 = time.time()
insertionSort(input3500)
end8 = time.time()

start9 = time.time()
insertionSort(input4000)
end9 = time.time()

start10 = time.time()
insertionSort(input4500)
end10 = time.time()

x = [100, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]
y4 = [end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10]
plt.plot(x, y4, marker='o')
plt.title('Insertion Sort')
plt.show()

print(end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10)