# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pWjSLPNa5e5tcPrTgEE-R4wRceWFE8n
"""

import time
import matplotlib.pyplot as plt

def mergeSort(input):
    if len(input) > 1:
        mid = len(input)//2
        left = input[:mid]
        right = input[mid:]

        mergeSort(left)
        mergeSort(right)

        i = 0
        j = 0
        k = 0
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                input[k] = left[i]
                i += 1
            else:
                input[k] = right[j]
                j += 1
            k += 1
        while i < len(left):
            input[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            input[k] = right[j]
            j += 1
            k += 1


start1 = time.time()
mergeSort(input100)
end1 = time.time()

start2 = time.time()
mergeSort(input500)
end2 = time.time()

start3 = time.time()
mergeSort(input1000)
end3 = time.time()

start4 = time.time()
mergeSort(input1500)
end4 = time.time()

start5 = time.time()
mergeSort(input2000)
end5 = time.time()

start6 = time.time()
mergeSort(input2500)
end6 = time.time()

start7 = time.time()
mergeSort(input3000)
end7 = time.time()

start8 = time.time()
mergeSort(input3500)
end8 = time.time()

start9 = time.time()
mergeSort(input4000)
end9 = time.time()

start10 = time.time()
mergeSort(input4500)
end10 = time.time()

x = [100, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]
y2 = [end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10]
plt.plot(x, y, marker='o')
plt.title('Merge Sort')
plt.show()

print(end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10)