# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pWjSLPNa5e5tcPrTgEE-R4wRceWFE8n
"""

import time
import matplotlib.pyplot as plt

start = time.time()

def partition(input, first, last):
    i = first-1
    pivot = input[last]

    for j in range(first, last):

        if input[j] <= pivot:
            i = i+1
            input[i], input[j] = input[j], input[i]
    input[i+1], input[last] = input[last], input[i+1]
    return (i+1)

def quickSort(input, first, last):
    if len(input) == 1: return input
    if first < last:

        partition_i = partition(input, first, last)
        quickSort(input, first, partition_i-1)
        quickSort(input, partition_i+1, last)

n = [100, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]

start1 = time.time()
quickSort(input100, 0, n[0]-1)
end1 = time.time()

start2 = time.time()
quickSort(input500, 0, n[1]-1)
end2 = time.time()

start3 = time.time()
quickSort(input1000, 0, n[2]-1)
end3 = time.time()

start4 = time.time()
quickSort(input1500, 0, n[3]-1)
end4 = time.time()

start5 = time.time()
quickSort(input2000, 0, n[4]-1)
end5 = time.time()

start6 = time.time()
quickSort(input2500, 0, n[5]-1)
end6 = time.time()

start7 = time.time()
quickSort(input3000, 0, n[6]-1)
end7 = time.time()

start8 = time.time()
quickSort(input3500, 0, n[7]-1)
end8 = time.time()

start9 = time.time()
quickSort(input4000, 0, n[8]-1)
end9 = time.time()

start10 = time.time()
quickSort(input4500, 0, n[9]-1)
end10 = time.time()

x = [100, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]
y1 = [end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10]
plt.plot(x, y1, marker='o')
plt.title('Quick Sort')
plt.show()

print(end1 - start1, end2 - start2, end3 - start3, end4 - start4, end5 - start5, end6 - start6, end7 - start7, end8 - start8
     , end9 - start9, end10 - start10)